config/routes.rb
AlrightValentine::Application.routes.draw do
  get "winks/create"
  resources :winks, :only => [:create]

  resources :messages, :only => [:new, :create, :destroy]

  get "/login" => "session#new"

  post "/login" => "session#create"

  delete "/logout" => "session#destroy"

  resources :users


  root :to => 'home#index'

end

app/models/image.rb
class Image
  include MongoMapper::EmbeddedDocument

  key :url, String
  key :user_id, String
  key :is_profile, Boolean, :default => false


end

app/models/message.rb
class Message
  include MongoMapper::Document

  key :content, String
  key :to_id, ObjectId
  key :from_id, ObjectId

  timestamps!

  belongs_to :to, :class_name  => "User"
  belongs_to :from, :class_name  => "User"
end

app/models/user.rb
class User
  include MongoMapper::Document
  include ActiveModel::SecurePassword
  key :first, String
  key :last, String
  key :email, String, :unique => true
  key :password_digest, String
  key :is_female, Boolean
  key :occupation, String
  key :sign_ins, Integer, :default => 0
  key :age, Integer
  key :ed_level, String
  key :movies, Array
  key :books, Array
  key :television, Array
  key :hobbies, String
  key :description, String
  key :tagline, String
  key :interested_female, Boolean
  many :images
  many :to_messages, :class_name => "Message", :foreign_key => "to_id"
  many :from_messages, :class_name => "Message", :foreign_key => "from_id"
  many :to_winks, :class_name => "Wink", :foreign_key => "to_id"
  many :from_winks, :class_name => "Wink", :foreign_key => "from_id"
  timestamps!
  has_secure_password
  attr_accessible :first, :last, :email, :password_confirmation, :password, :is_female, :occupation, :sign_ins, :age, :ed_level, :movies, :books, :television, :hobbies, :description, :tagline, :interested_female


  before_update :format_name, :format_interests



  def format_name
    self.first = self.first.capitalize if self.first.present?
    self.last = self.last.capitalize if self.first.present?
  end

  def format_interests
    self.books.map!{|x| x.capitalize}
    self.movies.map!{|x| x.capitalize}
    self.television.map!{|x| x.capitalize}
  end
end

app/models/wink.rb
class Wink
  include MongoMapper::Document

  key :to_id, String
  key :from_id, String

  belongs_to :to, :class_name  => "User"
  belongs_to :from, :class_name  => "User"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :logged_in

  private
  def logged_in
    session[:user_id].present? ? @current_user = User.find(session[:user_id]) : @current_user = nil
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user.present? && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      @user.sign_ins += 1
      @user.save
    end
    logged_in
  end

  def destroy
    session[:user_id] = nil
    logged_in
    redirect_to(root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(params[:user])
  end

  def show
    @user = User.find(params[:id])
    @ed_levels = ["High School", "Associate's Degree", "Bachelor's Degree", "Master's Degree", "PhD"]
  end

  def edit
    @ed_levels = ["High School", "Associate's Degree", "Bachelor's Degree", "Master's Degree", "PhD"]
    @user = User.find(params[:id])
  end



  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    redirect_to(user_path(@user))
  end
end

app/controllers/winks_controller.rb
class WinksController < ApplicationController
  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/winks_helper.rb
module WinksHelper
end

app/views/home/index.html.haml
%h1 Welcome to AlrightValentine

%p Readymade selfies fingerstache kitsch lo-fi bicycle rights. Asymmetrical sartorial sriracha, tumblr Truffaut gentrify Tonx fixie pour-over. Freegan pug tumblr, art party before they sold out Etsy dreamcatcher. Banjo dreamcatcher sartorial, plaid asymmetrical brunch freegan sriracha fashion axe cray. Brunch plaid polaroid VHS swag Neutra. IPhone pop-up try-hard disrupt synth asymmetrical. Pour-over raw denim semiotics meh, small batch Tonx ennui kale chips helvetica aesthetic.

.row
  .large-12.columns#home-holder
    #browse.make-left
      =link_to("Browse Singles", "#", :class => "button radius large alert")
      %p Banjo dreamcatcher sartorial, plaid asymmetrical brunch freegan sriracha fashion axe cray. Brunch plaid polaroid VHS swag Neutra. IPhone pop-up try-hard disrupt synth asymmetrical. Pour-over raw denim semiotics meh, small batch Tonx ennui kale chips helvetica aesthetic.
    #search.make-left
      =link_to("Search for Singles", "#", :class => "button radius large alert")
      %p eadymade selfies fingerstache kitsch lo-fi bicycle rights. Asymmetrical sartorial sriracha, tumblr Truffaut gentrify Tonx fixie pour-over. Freegan pug tumblr, art party before they sold out Etsy dreamcatcher.

app/views/layouts/_nav.html.haml
%nav.top-bar
  %ul.title-area
    / Title Area
    %li.name
      %h1
        = link_to("AlrightValentine", root_path)
    / Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        %span Menu
  %section.top-bar-section
    / Left Nav Section
    %ul.left
    / Right Nav Section
    %ul.right
      %li.divider.hide-for-small
      -if @current_user.nil?
        %li= link_to("Sign Up", new_user_path, :remote => true)
        %li.divider.hide-for-small
        %li= link_to("Login", login_path, :remote => true)
      -else
        %li= link_to("My Account", user_path(@current_user.id))
        %li.divider.hide-for-small
        %li= link_to("Log Out", logout_path, :method => "delete")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlrightValentine</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="nav_container">
    <%= render :partial => "layouts/nav" %>
  </div>
  <div class="row">
    <div class="large-4 large-centered columns">
      <div id="user_forms">
      </div>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <%= yield %>
    </div>
  </div>


</body>
</html>

app/views/messages/create.html.haml
%h1 Messages#create
%p Find me in app/views/messages/create.html.haml

app/views/messages/new.html.haml
%h1 Messages#new
%p Find me in app/views/messages/new.html.haml

app/views/session/_form.html.haml
= form_tag login_path, :remote => true do
  = label_tag :email
  = text_field_tag :email, nil, :autofocus => true
  = label_tag :password
  = password_field_tag :password
  = submit_tag "Alright", :class => "button radius large alert"

app/views/session/create.js.erb
var alert = $("<div>").addClass("alert-box alert radius");
<% if @current_user.present? %>
  console.log("if")
  alert.text("You have successfully Logged In!");
  $("#user_forms").empty().append(alert);
  alert.fadeOut(1000);
  // stuff that needs re-rendering now that there is a signed in user
  $("#nav_container").empty().append("<%= j render :partial => 'layouts/nav' %>")
  //first time signing in
  <% if @current_user.sign_ins == 1 %>
    var profile = $("<div>").append("Welcome! Click <a href='/users/<%= @current_user.id %>'>here</a> to create your profile");
    $("#user_forms").append(profile)
  <% end %>
<% else %>
  console.log("else")
  alert.text("Your Credentials Were Incorrect");
  $("#user_forms").prepend(alert);
  $("#user_forms").effect("shake", 500);
<% end %>

app/views/session/new.js.erb
$("#user_forms").empty().append("<%=j render :partial => 'session/form'  %>");

app/views/users/_form.html.haml
= form_for @user, :remote => true do |f|
  =f.label :email
  =f.text_field :email, :autofocus => true
  =f.label :password
  =f.password_field :password
  =f.label :password_confirmation
  =f.password_field :password_confirmation
  =f.submit "Sign Up", :class => "button radius alert large"

app/views/users/_info.html.haml
/ attr_accessible :first, :last, :email, :password_confirmation, :password, :is_female, :occupation, :sign_ins, :age, :ed_level, :movies, :books, :television, :hobbies, :description, :tagline, :interested_female
.row
  .large-6.columns
    %h1= "#{@user.first} #{@user.last}"
    %h3= "#{@user.tagline}"
  .large-6.columns
    -if @current_user == @user
      = link_to("Edit", edit_user_path, :remote => true, :class => "button radius large alert")
.row
  .large-6.columns
    %ul{:style => "list-style:none"}
      %li= "Age: #{@user.age}"
      %li= "Gender: #{@user.is_female ? 'Female' : 'Male'}"
      %li= "Occupation: #{@user.occupation}"
      %li= "Education Level: #{@user.ed_level}"
      %li= "Interested In: #{@user.interested_female ? 'Female' : 'Male'}"
  .large-6.columns
    %ul
      %li= "Hobbies: #{@user.hobbies}"
      %li= "Description: #{@user.description}"
.row
  .large-4.columns
    %h5 Movies
    %ol
      -@user.movies.each do |x|
        %li= x
  .large-4.columns
    %h5 Books
    %ol
      -@user.books.each do |x|
        %li= x
  .large-4.columns
    %h5 TV Shows
    %ol
      -@user.movies.each do |x|
        %li= x

app/views/users/_more_fields_form.html.haml
= form_for @user do |f|
  .row
    .large-6.columns
      %fieldset
        %legend About You
        = f.label :first
        = f.text_field :first, :autofocus => true
        = f.label :last
        = f.text_field :last
        .row
          .large-6.columns
            =label_tag "Gender:"
            .row
              .large-6.columns
                = f.label :is_female, "Male"
                = f.radio_button :is_female, "false"
              .large-6.columns
                = f.label :is_female, "Female"
                = f.radio_button :is_female, "true"
          .large-6.columns
            = f.label :age
            = f.number_field :age
        = f.label :occupation
        = f.text_field :occupation
        = f.label :ed_level, "Education Level"
        = f.select :ed_level, options_for_select(@ed_levels)
        %br
        %br
        .row
          .large-6.columns
            = label_tag "Looking for:"
            .row
              .large-6.columns
                = f.label :interested_female, "Male"
                = f.radio_button :interested_female, "false"
              .large-6.columns
                = f.label :interested_female, "Female"
                = f.radio_button :interested_female, "true"
          .large-6.columns
            = label_tag :image, "Choose a Profile Picture"
            = file_field_tag :image
    .large-6.columns
      %fieldset
        %legend Interests
        = f.label :hobbies
        = f.text_area :hobbies, :size => "30x30"
        = f.label :description
        = f.text_area :description, :size => "30x100"
        = f.label :tagline
        = f.text_field :tagline
  .row
    .large-12.columns
      %fieldset
        %legend Desert Island Picks
        .row
          .large-4.columns
            %fieldset
              %legend Top 5 Movies
              - 5.times do |x|
                = text_field_tag "user[movies][]", @user.movies[x], :placeholder => "#{x+1}."
          .large-4.columns
            %fieldset
              %legend Top 5 Books
              - 5.times do |x|
                = text_field_tag "user[books][]", @user.books[x], :placeholder => "#{x+1}."
          .large-4.columns
            %fieldset
              %legend Top 5 TV Shows
              - 5.times do |x|
                = text_field_tag "user[television][]", @user.television[x], :placeholder => "#{x+1}."
  .row
    .large-4.large-centered.columns
      = f.submit "Valentine", :class => "button radius alert large"

app/views/users/create.js.erb
<% if @user.valid? %>
  console.log("if")
  var alert = $("<div>").addClass("alert-box alert radius");
  alert.text("You have successfully Signed Up!");
  $("#user_forms").empty().append(alert);
  alert.fadeOut(1000);
<% else %>
  console.log("else")
  var ul = $("<ul>")
  <% @user.errors.messages.each do |k, v| %>
    var li = $("<li>").text("<%= k %> <%= v.first %>").addClass("alert-box alert radius");
    ul.prepend(li)
  <% end %>
  $("#user_forms").prepend(ul);
  $("#user_forms").effect("shake", 500);
<% end %>

app/views/users/edit.js.erb
$("#user_show").empty().append("<%= j render 'more_fields_form' %>");

app/views/users/new.js.erb
$("#user_forms").empty().append("<%=j render :partial => 'users/form'  %>");

app/views/users/show.html.haml
#user_show
  -if @current_user == @user && @current_user.sign_ins == 1 && @current_user.first.nil?
    %h3 Create your Profile
    = render :partial => "more_fields_form"
  -else
    = render :partial => "info"

app/views/winks/create.html.haml
%h1 Winks#create
%p Find me in app/views/winks/create.html.haml